//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaypointCreator.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CoreDBEntities : DbContext
    {
        public CoreDBEntities()
            : base("name=CoreDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<creature> creatures { get; set; }
        public DbSet<creature_linking_template> creature_linking_template { get; set; }
        public DbSet<creature_movement> creature_movement { get; set; }
        public DbSet<creature_movement_template> creature_movement_template { get; set; }
        public DbSet<creature_template> creature_template { get; set; }
        public DbSet<creature_linking> creature_linking { get; set; }
    }
}
